name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: '14.3.1'

      - name: Linting
        run: ./swiftformat . --lint

      - name: Testing Swift package
        run: xcodebuild test -scheme OptiDiff -destination 'platform=iOS Simulator,OS=16,name=iPhone 14'

      - name: Linting podspec
        run: |
          sudo gem install cocoapods
          pod lib lint --platforms=ios
